# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Piggy Slave's Blog
subtitle: ''
description: '大家好，我是粉红小猪Piggy Slave又简称p1slave, 我在这里记录分享自己的情感生活和写一些感悟随笔'
keywords:
author: p1slave
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://p1slave.com
permalink: :year-:month-:day-:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# Search
search:
  path: search.xml
  field: post
  content: true
  format: html

# Sitemaps - https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml
  #template: ./sitemap_template.xml
  rel: false
  tags: true
  categories: true

# Feed
feed:
  enable: true
  type: 
    - atom
    - rss2
  path: 
    - atom.xml
    - rss2.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:


# Encryption and Security
encrypt: # hexo-blog-encrypt
  abstract: This post is encrypted, password is required to continue reading.
  message: Ask the admin for password.
  # tags:
  # - {name: encryptAsDiary, password: passwordA}
  # - {name: encryptAsTips, password: passwordB}
  theme: xray
  wrong_pass_message: Oh, this is an invalid password. Check and try again, please.
  wrong_hash_message: Oh, these decrypted content cannot be verified, but you can still have a look.

# Watermark
# watermark:
#     enable: true
#     textEnable: true
#     rotate: -45
#     gravity: centre
#     directory:
#         - posts


# "hexo-web-push-notification": "^0.4.0",
# webPushNotification:
#   webpushrKey: "edfd362f037c44d6493ee2bd87bcd779"
#   webpushrAuthToken: "42492"
#   trackingCode: "BNdwGjEp_Yn0y89vfRj3Nt3-zJ1aW_dYZo9S-mqsIUTQUyR-R_63zp_XaRPkcO6XtjtMRDE0zDf7CffWPOE-0k0"